/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.example.demo.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverter;
import com.example.demo.model.Person.Ocupation.OcupationConverter;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 *
 * @author cesar.rodriguez
 */
@DynamoDBTable(tableName = "Person")
public class Person {

    private String id;
    private String name;
    private int age;
    private String cellphone;
    private Ocupation ocupation;

    public Person() {
    }

    @JsonCreator
    public Person(@JsonProperty("id") String id, @JsonProperty("name") String name,
            @JsonProperty("age") int age, @JsonProperty("cellphone") String cellphone) {
        this.id = id;
        this.name = name;
        this.age = age;
        this.cellphone = cellphone;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute(attributeName = "name")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @DynamoDBAttribute(attributeName = "age")
    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    @DynamoDBAttribute(attributeName = "cellphone")
    public String getCellphone() {
        return cellphone;
    }

    public void setCellphone(String cellphone) {
        this.cellphone = cellphone;
    }

    @DynamoDBTypeConverted(converter = OcupationConverter.class)
    @DynamoDBAttribute(attributeName = "ocupation")
    public Ocupation getOcupation() {
        return ocupation;
    }

    public void setOcupation(Ocupation ocupation) {
        this.ocupation = ocupation;
    }

    static public class Ocupation {

        private String profesion;
        private String cargo;

        public String getProfesion() {
            return profesion;
        }

        public void setProfesion(String profesion) {
            this.profesion = profesion;
        }

        public String getCargo() {
            return cargo;
        }

        public void setCargo(String cargo) {
            this.cargo = cargo;
        }

        static public class OcupationConverter implements DynamoDBTypeConverter<String, Ocupation> {

            @Override
            public String convert(Ocupation object) {
                Ocupation itemOcupation = (Ocupation) object;
                String ocupation = null;
                try {
                    if (itemOcupation != null) {
                        ocupation = String.format("%s x %s", itemOcupation.getProfesion(), itemOcupation.getCargo());
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
                return ocupation;
            }

            @Override
            public Ocupation unconvert(String s) {
                Ocupation itemOcupation = new Ocupation();
                try {
                    if (s != null && s.length() != 0) {
                        String[] data = s.split("x");
                        itemOcupation.setCargo(data[0].trim());
                        itemOcupation.setProfesion(data[1].trim());
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }

                return itemOcupation;
            }

        }

    }

}
