package com.example.demo.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "ProductInfo")
public class ProductInfo {
    private String id;
    private String test;

    public ProductInfo() {
    }

    
    
    public ProductInfo(String test) {
        this.test = test;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    @DynamoDBAttribute
    public String getTest() {
        return test;
    }

    public void setId(String id) {
        this.id = id;
    }

    public void setTest(String test) {
        this.test = test;
    }

    @Override
    public String toString() {
        return "ProductInfo{" + "id=" + id + ", test=" + test + '}';
    }

    public ProductInfo(String id, String test) {
        this.id = id;
        this.test = test;
    }
    
}
