/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.example.demo.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 *
 * @author cesar.rodriguez
 */
@DynamoDBTable(tableName = "test")
public class Test {

    private String myId;
    private String nameTest;
    private String descTest;
    private int numTest;

    public Test() {
    }

    public Test(@JsonProperty("myId") String myId, @JsonProperty("nameTest") String nameTest, @JsonProperty("descTest") String descTest,
            @JsonProperty("numTest") int numTest) {
        this.myId = myId;
        this.nameTest = nameTest;
        this.descTest = descTest;
        this.numTest = numTest;
    }

    //@DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName="myId")
    public String getMyId() {
        return myId;
    }

    public void setMyId(String myId) {
        this.myId = myId;
    }

    //@DynamoDBIndexHashKey(globalSecondaryIndexName = "NameIndex", attributeName = "nameTest")
    @DynamoDBRangeKey(attributeName = "nameTest")
    public String getNameTest() {
        return nameTest;
    }

    public void setNameTest(String nameTest) {
        this.nameTest = nameTest;
    }

    //@DynamoDBIndexRangeKey(globalSecondaryIndexName = "NameIndex", attributeName = "descTest")
    //@DynamoDBAttribute(attributeName="descTest")
    @DynamoDBIndexRangeKey(localSecondaryIndexName = "DescIndex",attributeName = "descTest")
    public String getDescTest() {
        return descTest;
    }

    public void setDescTest(String descTest) {
        this.descTest = descTest;
    }

    @DynamoDBAttribute(attributeName="numTest")
    public int getNumTest() {
        return numTest;
    }

    public void setNumTest(int numTest) {
        this.numTest = numTest;
    }

}
