/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.example.demo.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 *
 * @author cesar.rodriguez
 */
@DynamoDBTable(tableName = "test")
public class Test {

    private String myId;
    private String nameTest;
    private String desc;
    private int numTest;

    public Test() {
    }

    public Test(@JsonProperty("myId") String myId, @JsonProperty("name") String name, @JsonProperty("desc") String desc,
            @JsonProperty("numTest") int numTest) {
        this.myId = myId;
        this.nameTest = name;
        this.desc = desc;
        this.numTest = numTest;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getMyId() {
        return myId;
    }

    public void setMyId(String myId) {
        this.myId = myId;
    }

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "TestBy-Name-Index", attributeName = "nameTest")
    public String getNameTest() {
        return nameTest;
    }

    public void setNameTest(String name) {
        this.nameTest = name;
    }

    @DynamoDBIndexRangeKey(globalSecondaryIndexName = "TestBy-Name-Index", attributeName = "desc")
    @DynamoDBAttribute
    public String getDesc() {
        return desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

    @DynamoDBAttribute
    public int getNumTest() {
        return numTest;
    }

    public void setNumTest(int numTest) {
        this.numTest = numTest;
    }

}
